/// Bu sınıf, Firebase'in platforma özel konfigürasyonlarını içerir.
/// Platforma özel Firebase ayarlarını dinamik olarak almak için kullanılır.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASV2ckOnOJy7Wf7EDKv5ssFqqVnx-SWFQ',
    appId: '1:632831101427:web:0cf51a1ae374bf01e0aa86',
    messagingSenderId: '632831101427',
    projectId: 'newsapplogin-8e4d1',
    authDomain: 'newsapplogin-8e4d1.firebaseapp.com',
    storageBucket: 'newsapplogin-8e4d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJ_9wkHeYGFV6saGyjgc8F3nLjjzkBKE',
    appId: '1:632831101427:android:b643385107b5419ae0aa86',
    messagingSenderId: '632831101427',
    projectId: 'newsapplogin-8e4d1',
    storageBucket: 'newsapplogin-8e4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4VTKLROG5FsswC_HQ1m7AakVBslrlPI',
    appId: '1:632831101427:ios:d36ddcd447a8ea02e0aa86',
    messagingSenderId: '632831101427',
    projectId: 'newsapplogin-8e4d1',
    storageBucket: 'newsapplogin-8e4d1.firebasestorage.app',
    iosBundleId: 'com.example.btNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4VTKLROG5FsswC_HQ1m7AakVBslrlPI',
    appId: '1:632831101427:ios:d36ddcd447a8ea02e0aa86',
    messagingSenderId: '632831101427',
    projectId: 'newsapplogin-8e4d1',
    storageBucket: 'newsapplogin-8e4d1.firebasestorage.app',
    iosBundleId: 'com.example.btNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASV2ckOnOJy7Wf7EDKv5ssFqqVnx-SWFQ',
    appId: '1:632831101427:web:a5f6e15e2a124f35e0aa86',
    messagingSenderId: '632831101427',
    projectId: 'newsapplogin-8e4d1',
    authDomain: 'newsapplogin-8e4d1.firebaseapp.com',
    storageBucket: 'newsapplogin-8e4d1.firebasestorage.app',
  );
}
